name: https://jfavre.github.io/InSitu-Vis-Tutorial/slides/

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./slides/src/202512/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm & deps
        run: |
          npm i -g pnpm
          cd ../install
          pnpm install
          cd -
          rm node_modules          
          pnpm install

      - name: Build Slidev
        run: |
          pnpm build --base /${{github.event.repository.name}}/slides/ --out ../../dist/slides
          pwd
          ls -l ../../dist/slides
          ls -l ../../dist/

      - name: Setup Github Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /home/runner/work/InSitu-Vis-Tutorial/InSitu-Vis-Tutorial/slides/dist/

#       - name: Build PDF
#         run: |
#           pnpm exec playwright install
#           pnpm export --output /tmp/InSitu-Vis-Tutorial.pdf --format pdf 
# 
#       - name: Upload PDF artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: InSitu-Vis-Tutorial.pdf
#           path: /tmp/InSitu-Vis-Tutorial.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}slides/
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
